services:
  redis:
    image: redis
    ports:
          - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/5672'"]
      interval: 2s
      timeout: 2s
      retries: 30

  pollservice:
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    build: 
      context: .
      dockerfile: docker/pollservice
    image: magnussletten/pollservice:latest 
    ports:
      - "8080:8080"
    env_file:
      - .env 
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"

  caddy:
    depends_on:
      - pollservice
    image: polling-caddy
    build:
      context: .
      dockerfile: docker/caddy.dockerfile
    ports:
      - "80:80"
      - "443:443"
    container_name: polling-caddy
